# Generated by Django 5.2 on 2025-08-05 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Billtable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_id', models.CharField(blank=True, editable=False, max_length=4, unique=True)),
                ('loan_id', models.CharField(blank=True, editable=False, max_length=6, unique=True)),
                ('created', models.DateTimeField(auto_now=True)),
                ('fullname', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=40)),
                ('phone1', models.CharField(max_length=15)),
                ('phone2', models.CharField(max_length=15)),
                ('dateofbirth', models.DateField()),
                ('address', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='images/')),
                ('nominee_name', models.CharField(max_length=15)),
                ('nominee_relation', models.CharField(max_length=15)),
                ('nominee_phone', models.CharField(max_length=15)),
                ('nominee_address', models.CharField(max_length=100)),
                ('ornament_image', models.ImageField(upload_to='ornament_images/')),
                ('ornament_details', models.CharField(max_length=100)),
                ('scheme', models.CharField(max_length=15)),
                ('amount', models.CharField(max_length=15)),
                ('duration', models.CharField(max_length=15)),
                ('status', models.BooleanField(default=True)),
            ],
        ),
    ]
