# Generated by Django 5.2 on 2025-08-08 12:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='billtable',
            old_name='scheme',
            new_name='initial_intrest',
        ),
        migrations.AddField(
            model_name='billtable',
            name='current_intrest',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='billtable',
            name='payed_amount',
            field=models.CharField(blank=True, default='0', max_length=15),
        ),
        migrations.AddField(
            model_name='billtable',
            name='total_amount',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.CreateModel(
            name='PaymentTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now=True)),
                ('current_intrest', models.CharField(max_length=15)),
                ('amount', models.CharField(max_length=15)),
                ('payment_method', models.CharField(max_length=25)),
                ('notes', models.CharField(max_length=50)),
                ('billtable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='bill.billtable')),
            ],
        ),
    ]
