# Generated by Django 5.2 on 2025-08-11 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0002_rename_scheme_billtable_initial_intrest_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='billtable',
            name='ornament_weight',
            field=models.CharField(default=1, max_length=15),
            preserve_default=False,
        ),
    ]
