# Generated by Django 5.2 on 2025-08-11 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0003_billtable_ornament_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='billtable',
            name='emi_due_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
