# Generated by Django 5.2 on 2025-08-23 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0005_alter_billtable_amount_alter_billtable_created_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='billtable',
            name='ornament_net_weight',
            field=models.CharField(default=10, max_length=15),
            preserve_default=False,
        ),
    ]
