# Generated by Django 5.2 on 2025-08-23 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0006_billtable_ornament_net_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billtable',
            name='dateofbirth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='billtable',
            name='email',
            field=models.EmailField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='billtable',
            name='phone2',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
