# Generated by Django 5.2 on 2025-08-23 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0008_billtable_bangle_count_billtable_bangle_weight_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='billtable',
            old_name='ornament_details',
            new_name='others_details',
        ),
        migrations.RemoveField(
            model_name='billtable',
            name='others',
        ),
        migrations.AddField(
            model_name='billtable',
            name='chain_count',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
