# Generated by Django 5.2 on 2025-08-23 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0009_rename_ornament_details_billtable_others_details_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billtable',
            name='others_details',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
