# Generated by Django 5.2 on 2025-08-25 05:01

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0010_alter_billtable_others_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='billtable',
            name='intrest_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=12, null=True),
        ),
    ]
