# Generated by Django 5.2 on 2025-08-25 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0011_billtable_intrest_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymenttable',
            name='current_intrest',
        ),
    ]
