# Generated by Django 5.2 on 2025-09-16 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0012_remove_paymenttable_current_intrest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billtable',
            name='customer_id',
            field=models.CharField(max_length=4, unique=True),
        ),
        migrations.AlterField(
            model_name='billtable',
            name='loan_id',
            field=models.CharField(blank=True, editable=False, max_length=10, unique=True),
        ),
    ]
